### ISSUE TITLE
Errors when uploading sources via spreadsheet into a collection

### ISSUE THREAD

**Issue by AnissaPierre** [mitmedialab/MediaCloud-Web-Tools#1307] opened 2018-09-26 18:05 UTC
Not sure what the error is because the message is still blank
<img width="1397" alt="screen shot 2018-09-26 at 2 03 32 pm" src="https://user-images.githubusercontent.com/25494330/46099594-2b90d500-c195-11e8-87df-94aa56c0ccdf.png">

**Comment by AnissaPierre** [comment] 2018-09-26 18:05
<img width="1317" alt="screen shot 2018-09-26 at 2 05 41 pm" src="https://user-images.githubusercontent.com/25494330/46099627-45321c80-c195-11e8-8e64-35674244f4fc.png">

**Comment by cindyloo** [comment] 2018-10-01 16:19
this is a result of not having a media name along with a media url in the csv file

**Comment by cindyloo** [comment] 2018-10-01 16:34
duplicate of #1302

**Comment by AnissaPierre** [comment] 2018-10-01 16:35
Hi Cindy,

Thanks again for working on this. I remember we talked about this but I'm not sure if we came to a solution. When you upload the CSV, the name should be blank. That's what our support page says and it has worked without a source name before. 

Best,
Anissa

**Comment by cindyloo** [comment] 2018-10-01 16:58
yes - just confirming all pathways

**Closed by cindyloo** 2018-10-01 16:58 UTC
Labels: bug, sources app

**Comment by AnissaPierre** [comment] 2018-10-01 17:48
Oh, okay. :) 

-Anissa
