### ISSUE TITLE
Source Content Tab on Media Source shows innacurate dates

### ISSUE THREAD

**Issue by titinfoundation** [mitmedialab/MediaCloud-Web-Tools#1980] opened 2020-09-02 20:07 UTC
[
<img width="1272" alt="Screen Shot 2020-09-02 at 3 59 35 PM" src="https://user-images.githubusercontent.com/64150394/92031243-4fbc9f80-ed36-11ea-8f20-686f652fdf70.png">
<img width="1184" alt="Screen Shot 2020-09-02 at 4 01 46 PM" src="https://user-images.githubusercontent.com/64150394/92031246-50edcc80-ed36-11ea-9525-e694bff0572b.png">

](url)

some times the dates are into the future, sometimes the dates are in the past even if they are supposed working currently

**Comment by dsjen** [comment] 2020-09-03 15:07
Duplicate of #1951

**Closed by dsjen** 2020-09-03 15:07 UTC
Labels: bug, duplicate
