### ISSUE TITLE
Unable to update source URL (URL was too similar?)

### ISSUE THREAD

**Issue by AnissaPierre** [mitmedialab/MediaCloud-Web-Tools#1506] opened 2019-03-27 15:47 UTC
This source: [https://sources.mediacloud.org/#/sources/59245](https://sources.mediacloud.org/#/sources/59245)

I wanted to update the URL from http://angonoticias.com/ to http://www.angonoticias.com/ because the former doesn't work. Source manager was throwing an error message that the source already existed, although that exact URL was not in the system. Adding a # or ? after the backslash enabled me to save the URL.

**Comment by hroberts** [comment] 2019-03-29 19:56
The problem is that there is another media source in the system with the
http://www.angonoticias.com/
<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.angonoticias.com_&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=0c5FW2CrwCh84ocLICzUHjcwKK-QMUDy4RRw_n18mMo&m=v84OrtKZ9FIdoholgPR6T7zNwEMYzTwJX4MIlwVCqTE&s=ZeviYZcUGy-oIYl-fM8mP3pEvVx2GGzqjfK8tnwSmAU&e=>
url.
But it is one of the duplicate container media sources that we don't expose
via the sources tool because it is either just a duplicate of another
source or it is only a container for spidered stories and does not actively
collect any rss feeds.

This is precisely one of the problems that we are trying to solve with the
domain based media stuff.  We won't have to have all of these extra,
duplicate media source sitting around in the database causing hacks like
adding a '#' to the end of the url to make it update.

-hal

On Wed, Mar 27, 2019 at 10:47 AM AnissaPierre <notifications@github.com>
wrote:

> This source: https://sources.mediacloud.org/#/sources/59245
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__sources.mediacloud.org_-23_sources_59245&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=0c5FW2CrwCh84ocLICzUHjcwKK-QMUDy4RRw_n18mMo&m=v84OrtKZ9FIdoholgPR6T7zNwEMYzTwJX4MIlwVCqTE&s=U871nlE8v9vfzlnUpfd08DrHVT3tsZqdkeeND3j0z6M&e=>
>
> I wanted to update the URL from http://angonoticias.com/
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__angonoticias.com_&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=0c5FW2CrwCh84ocLICzUHjcwKK-QMUDy4RRw_n18mMo&m=v84OrtKZ9FIdoholgPR6T7zNwEMYzTwJX4MIlwVCqTE&s=eo72oXWEXdajVahIBaSnU3zDL8KwEIJbobJ-RCIhBmA&e=>
> to http://www.angonoticias.com/
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.angonoticias.com_&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=0c5FW2CrwCh84ocLICzUHjcwKK-QMUDy4RRw_n18mMo&m=v84OrtKZ9FIdoholgPR6T7zNwEMYzTwJX4MIlwVCqTE&s=ZeviYZcUGy-oIYl-fM8mP3pEvVx2GGzqjfK8tnwSmAU&e=>
> because the former doesn't work. Source manager was throwing an error
> message that the source already existed, although that exact URL was not in
> the system. Adding a # or ? after the backslash enabled me to save the URL.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mitmedialab_MediaCloud-2DWeb-2DTools_issues_1506&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=0c5FW2CrwCh84ocLICzUHjcwKK-QMUDy4RRw_n18mMo&m=v84OrtKZ9FIdoholgPR6T7zNwEMYzTwJX4MIlwVCqTE&s=fzG02-t_5dqb_Wj4Fezr1S6u2gCnVKg8GjPGpTUZ2fo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABvvT-5F7AzymJAq1k-2DUEnOsDQBMoMviVUks5va5KNgaJpZM4cOJOe&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=0c5FW2CrwCh84ocLICzUHjcwKK-QMUDy4RRw_n18mMo&m=v84OrtKZ9FIdoholgPR6T7zNwEMYzTwJX4MIlwVCqTE&s=a0UEk20pJyOkLkKMRTqVKljjaZbS1V6xUUZ4Qe_c8yo&e=>
> .
>


-- 
Hal Roberts
Fellow
Berkman Klein Center for Internet & Society
Harvard University

**Closed** 2019-03-29 19:56 UTC
